export const CAMBIAR_TITULO_AUDITORIA = "CAMBIAR_TITULO_AUDITORIA"
export const CARGANDO_FIL_VISTAS_AUDITORIA = "CARGANDO_FIL_VISTAS_AUDITORIA"
export const CARGANDO_FIL_TIEMPO_AUDITORIA = "CARGANDO_FIL_TIEMPO_AUDITORIA"
export const CARGANDO_FIL_USUGAN_AUDITORIA = "CARGANDO_FIL_USUGAN_AUDITORIA"
export const CARGANDO_FIL_USUPER_AUDITORIA = "CARGANDO_FIL_USUPER_AUDITORIA"


export const OBTENER_FIL_VISTAS_AUDITORIA = "OBTENER_FIL_VISTAS_AUDITORIA"
export const OBTENER_FIL_TIEMPO_AUDITORIA = "OBTENER_FIL_TIEMPO_AUDITORIA"
export const OBTENER_FIL_USUGAN_AUDITORIA = "OBTENER_FIL_USUGAN_AUDITORIA"
export const OBTENER_FIL_USUPER_AUDITORIA = "OBTENER_FIL_USUPER_AUDITORIA"


export const DATA_FIL_VISTAS_AUDITORIA = "DATA_FIL_VISTAS_AUDITORIA"
export const DATA_FIL_TIEMPO_AUDITORIA = "DATA_FIL_TIEMPO_AUDITORIA"
export const DATA_FIL_USUGAN_AUDITORIA = "DATA_FIL_USUGAN_AUDITORIA"
export const DATA_FIL_USUPER_AUDITORIA = "DATA_FIL_USUPER_AUDITORIA"

