export const SELECCIONAR_MODULO = 'SELECCIONAR_MODULO';
export const OBTENER_SELECCION_MODULO = 'OBTENER_SELECCION_MODULO';
export const SELECCIONAR_AGREGAR_FAVORITO = 'SELECCIONAR_AGREGAR_FAVORITO';
export const SELECCIONAR_FAVORITOS = 'SELECCIONAR_FAVORITOS';
export const SELECCIONAR_MODULO_ESPECIFICO = 'SELECCIONAR_MODULO_ESPECIFICO';